# Loggion config
logging:
  level:
    root: INFO
  file:
    name: logs/persona.log

# REST Config
server:
  port: 3000

spring:
  application:
    name: PersonApp API
  main:
    allow-circular-references: true

  # MariaDB Config
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:${MARIADB_PORT:3307}/persona_db
    username: persona_db
    password: persona_db
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

  # MongoDB Config
  data:
    mongodb:
      authentication-database: admin
      username: persona_db
      password: persona_db
      database: persona_db
      port: ${MONGODB_PORT:27017}
      host: ${MONGODB_HOST:localhost}

# SWAGGER (OpenAPI) Config
springdoc:
  api-docs:
    path: /api-docs